[package]
name = "whirlpool-asm"
version = "0.4.0"
authors = ["The RustCrypto Devs"]
license = "MIT"
description = "Assembly implementation of Whirlpool compression function"
documentation = "https://docs.rs/whirlpool-asm"
repository = "https://github.com/RustCrypto/asm-hashes"
keywords = ["crypto", "whirlpool", "asm"]
categories = ["cryptography", "no-std"]

[dependencies]
generic-array = "0.10"

[build-dependencies]
cc = "1.0"

[badges]
travis-ci = { repository = "RustCrypto/asm-hashes" }
