[package]
name = "whirlpool-asm"
version = "0.1.0"
authors = ["The RustCrypto Devs"]
license = "MIT/Apache-2.0"
description = "Assembly implementation of Whirlpool hash function"
documentation = "https://docs.rs/whirlpool-asm"
repository = "https://github.com/RustCrypto/asm-hashes"
keywords = ["crypto", "whirlpool", "hash", "digest"]
categories = ["cryptography", "no-std"]

[dependencies]
digest = "0.5"
generic-array = "0.7"
digest-buffer = "0.3"

[dev-dependencies]
crypto-tests = "0.4"

[build-dependencies]
gcc = "0.3"

[badges]
travis-ci = { repository = "RustCrypto/hashes" }
