[package]
name = "whirlpool-asm"
version = "0.2.2"
authors = ["The RustCrypto Devs"]
license = "MIT"
description = "Assembly implementation of Whirlpool compression function"
documentation = "https://docs.rs/whirlpool-asm"
repository = "https://github.com/RustCrypto/asm-hashes"
keywords = ["crypto", "whirlpool", "asm"]
categories = ["cryptography", "no-std"]

[dependencies]
generic-array = "0.7"

[build-dependencies]
gcc = "0.3"

[badges]
travis-ci = { repository = "RustCrypto/asm-hashes" }
