[package]
name = "sha2-asm"
version = "0.3.0"
authors = ["The RustCrypto Devs"]
license = "MIT"
description = "Assembly implementation of SHA-2 compression functions"
documentation = "https://docs.rs/sha2-asm"
repository = "https://github.com/RustCrypto/asm-hashes"
keywords = ["crypto", "sha2", "asm"]
categories = ["cryptography", "no-std"]

[dependencies]
generic-array = "0.8"

[build-dependencies]
cc = "1.0"

[badges]
travis-ci = { repository = "RustCrypto/asm-hashes" }
