[package]
name = "md5-asm"
version = "0.1.0"
authors = ["The RustCrypto Devs"]
license = "MIT/Apache-2.0"
description = "Assembly implementation of MD5 hash function"
documentation = "https://docs.rs/md5-asm"
repository = "https://github.com/RustCrypto/asm-hashes"
keywords = ["crypto", "md5", "hash", "digest"]
categories = ["cryptography", "no-std"]

[dependencies]
digest = "0.5"
generic-array = "0.7"
byte-tools = "0.1"
digest-buffer = "0.3"

[dev-dependencies]
crypto-tests = "0.4"

[build-dependencies]
gcc = "0.3"

[badges]
travis-ci = { repository = "RustCrypto/hashes" }
