[package]
name = "md5-asm"
version = "0.2.1"
authors = ["The RustCrypto Devs"]
license = "MIT"
description = "Assembly implementation of MD5 compression function"
documentation = "https://docs.rs/md5-asm"
repository = "https://github.com/RustCrypto/asm-hashes"
keywords = ["crypto", "md5", "asm"]
categories = ["cryptography", "no-std"]

[dependencies]
generic-array = "0.7"

[build-dependencies]
gcc = "0.3"

[badges]
travis-ci = { repository = "RustCrypto/asm-hashes" }
